/* ============================================================
   rcpl season 5 — static reference data
   ------------------------------------------------------------
   regenerated by the Season Rollover tool at season's end.
   nothing here changes at runtime — load it before the main
   inline script in index.html.
   ============================================================ */

// ============================== MANAGER CAREER HISTORY ==============================
const SEASON_OUTCOMES = {
  arka: [
    { season: 1, team: 'pbks', w: 14, m: 16, outcome: 'finalist' },
    { season: 2, team: 'pbks', w: 15, m: 16, outcome: 'finalist' },
    { season: 3, team: 'pbks', w: 13, m: 16, outcome: 'finalist' },
    { season: 4, team: 'pbks', w: 8,  m: 15, outcome: 'eliminator' }
  ],
  arkaparno: [
    { season: 1, team: 'kkr', w: 11, m: 16, outcome: 'qualifier' },
    { season: 2, team: 'kkr', w: 9,  m: 15, outcome: 'eliminator' },
    { season: 4, team: 'kkr', w: 8,  m: 14, outcome: 'group' }
  ],
  tuhinangshu: [
    { season: 1, team: 'rcb', w: 8,  m: 15, outcome: 'qualifier' },
    { season: 2, team: 'rcb', w: 13, m: 17, outcome: 'champion' },
    { season: 3, team: 'kkr', w: 14, m: 17, outcome: 'champion' },
    { season: 4, team: 'lsg', w: 11, m: 17, outcome: 'finalist' }
  ],
  deeptayan: [
    { season: 1, team: 'mi', w: 11, m: 17, outcome: 'champion' },
    { season: 2, team: 'mi', w: 9,  m: 16, outcome: 'qualifier' },
    { season: 4, team: 'mi', w: 11, m: 16, outcome: 'qualifier' }
  ],
  rio: [
    { season: 3, team: 'rcb', w: 12, m: 16, outcome: 'qualifier' },
    { season: 4, team: 'rcb', w: 12, m: 16, outcome: 'champion' }
  ],
  adarsh: [
    { season: 3, team: 'dc',  w: 6,  m: 14, outcome: 'group' },
    { season: 4, team: 'dc',  w: 7,  m: 14, outcome: 'group' }
  ],
  prajyot: [
    { season: 3, team: 'csk', w: 1,  m: 14, outcome: 'group' },
    { season: 4, team: 'csk', w: 1,  m: 14, outcome: 'group' }
  ],
  rishit: [
    { season: 3, team: 'srh', w: 6,  m: 14, outcome: 'group' },
    { season: 4, team: 'rr',  w: 6,  m: 14, outcome: 'group' }
  ],
  neil: [
    { season: 3, team: 'rr',  w: 6,  m: 15, outcome: 'eliminator' },
    { season: 4, team: 'gt',  w: 4,  m: 14, outcome: 'group' }
  ],
  adi: [
    { season: 4, team: 'srh', w: 5,  m: 14, outcome: 'group' }
  ]
};

// ============================== HISTORICAL BASELINE (S1–S3) ==============================
const HISTORICAL_RATING = {
  pbks: 94,  kkr:  77,  rcb:  75,  lsg:  62,  mi:   54,  gt:   51,  dc:   44,  rr:   44,  csk:  42,  srh:  23
};

// Career m/w = complete S1–S4 (group + playoffs). runs/wkts/eco span S1–S4 too, with two
// known gaps: S1 wickets were never recorded (so wkts omits S1 for the 8 original teams),
// and S4 detail comes from a partial export (snapshot, missing ~10 league games + the Final).
// Added new tracking columns: battedInns (defaults to m), wktsLost (for RPW), fifties, and hs (High Score).
const CAREER_STATS = {
  pbks: { m:63, w:50, runs:2774, wkts:346, eco:7.87, nrr: 3.268, battedInns:63, wktsLost:null, fifties:19, hs:89 },
  kkr:  { m:62, w:42, runs:2393, wkts:223, eco:8.16, nrr: 1.372, battedInns:62, wktsLost:null, fifties:18, hs:72 },
  rcb:  { m:64, w:45, runs:2749, wkts:227, eco:8.05, nrr: 2.094, battedInns:64, wktsLost:null, fifties:14, hs:72 },
  mi:   { m:63, w:33, runs:2392, wkts:235, eco:8.58, nrr: 0.304, battedInns:63, wktsLost:null, fifties:8,  hs:65 },
  dc:   { m:56, w:27, runs:1723, wkts:141, eco:9.34, nrr:-1.179, battedInns:56, wktsLost:null, fifties:8,  hs:73 },
  rr:   { m:57, w:20, runs:1888, wkts:173, eco:8.99, nrr:-1.246, battedInns:57, wktsLost:null, fifties:4,  hs:78 },
  csk:  { m:56, w:12, runs:1416, wkts:209, eco:8.80, nrr:-2.519, battedInns:56, wktsLost:null, fifties:3,  hs:65 },
  srh:  { m:56, w:14, runs:1545, wkts:158, eco:10.00,nrr:-3.302, battedInns:56, wktsLost:null, fifties:3,  hs:53 },
  lsg:  { m:17, w:11, runs: 626, wkts: 71, eco:8.00, nrr: 1.884, battedInns:17, wktsLost:null, fifties:0,  hs:0  },
  gt:   { m:14, w:4,  runs: 470, wkts: 36, eco:9.55, nrr:-1.650, battedInns:14, wktsLost:null, fifties:0,  hs:0  }
};
// ============================== HEAD-TO-HEAD (S1–S4 cumulative) ==============================
// Wins by the row team over the column team across S1–S4 (group stage + playoffs).
// S1–S3 from the league sheet; S4 from the recovered export (partial — 60/70 league + 3/4 playoffs).
// LSG & GT history begins in S4. Live S5 meetings are added on top at runtime.
const HISTORICAL_H2H = {
  pbks: { kkr:8, mi:4, rcb:6, dc:3, csk:5, rr:5, srh:5, lsg:0, gt:0 },
  kkr:  { pbks:1, mi:4, rcb:3, dc:2, csk:5, rr:5, srh:5, lsg:0, gt:2 },
  mi:   { pbks:4, kkr:4, rcb:2, dc:3, csk:4, rr:5, srh:5, lsg:0, gt:1 },
  rcb:  { pbks:1, kkr:3, mi:6, dc:2, csk:5, rr:5, srh:7, lsg:1, gt:1 },
  dc:   { pbks:1, kkr:1, mi:1, rcb:1, csk:3, rr:1, srh:2, lsg:0, gt:2 },
  csk:  { pbks:0, kkr:0, mi:2, rcb:0, dc:1, rr:3, srh:5, lsg:0, gt:0 },
  rr:   { pbks:1, kkr:1, mi:1, rcb:0, dc:4, csk:3, srh:3, lsg:0, gt:1 },
  srh:  { pbks:1, kkr:0, mi:0, rcb:0, dc:2, csk:2, rr:2, lsg:0, gt:1 },
  lsg:  { pbks:1, kkr:1, mi:1, rcb:1, dc:0, csk:1, rr:2, srh:1, gt:1 },
  gt:   { pbks:1, kkr:0, mi:0, rcb:0, dc:0, csk:1, rr:0, srh:0, lsg:1 },
};
